language: node_js

script:
  # build my resume(s)
  - npm run build
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch output/.nojekyll
  # github pages needs this file so it knows the domain name
  - echo resume.jacobfischer.me >> output/CNAME

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local-dir: output/
  on:
    branch: master
