language: node_js
node_js:
  - "6.9.2"

script:
  - bash -x ./setup.sh
  - bash -x ./build.sh

before_deploy:
  - bash -x pre-deploy.sh

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  on:
    branch: master
